# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a863413c794a43486c08c931ef43a8dc7f76303134edecb94f435f5ac822ea35f229dde1df262ec495ed4d72613b6fc6049509f417bb7eb36f14414b560869a5

test:
  secret_key_base: 85a1927f53a7d40ac63906c5faa7b8098ed770cfc55cef8c2c7bea143c13741c316a34b0c5513869339953d49c7630b0b02d93eed8d96685b04e5556d1a4fd9f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
